### ISSUE TITLE
Question about Python environments

### ISSUE THREAD

**Issue by lervag** [HiPhish/debugpy.nvim#3]
Debugpy requires the debugpy Python package. That's not surprising(!). However, I'm a little bit confused as to how to think of it.

Given a project `foobar`; I would typically use virtual environments to keep it clean. Do I understand correctly that the suggested practise is to install `debugpy` within the virtual environment? And to have it as a `dev` dependency (in the cases where I distinguish it like that)?

**Comment by HiPhish** [comment]
It's entirely up to you, this plugin has no particular demands on how you manage debugpy. Personally (and this is purely how I handle it), I install debugpy in the venv, but I don't put it in any of my requirements files. A development dependency to me is something that everyone agrees on for development, like a test framework or a linter. The debugger is a personal choice. Unless you actually use it as a library in your code of course.

But yeah, that's just like my opinion,  man.

**Comment by lervag** [comment]
Thanks for sharing your opinion; I think you make a good point about the dev dependencies, and I'll probably do things similarly to you.
